[package]
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
license = "TBD"
name = "springql-core"
version = "0.1.0"

edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

chrono = "0.4"

serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
