[package]
name = "springql-test-logger"
version = "0.4.0"

authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
license = "MIT OR Apache-2.0"

edition = "2021"

publish = false

[dependencies]
env_logger = "0.10"
log = "0.4"

log-panics = "2.0"
