[package]
name = "springql-core"
version = "0.1.0"

authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
license = "MIT OR Apache-2.0"

edition = "2021"

categories = ["embedded"]
description = "SpringQL: Open-source stream processor for IoT devices and in-vehicle computers"
documentation = "https://docs.rs/springql-core"
keywords = ["springql", "stream-processing"] # up to 5 keywords, each keyword should have <= 20 chars
repository = "https://github.com/SpringQL/SpringQL"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

chrono = "0.4"

serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = "1.0"

derive-new = "0.5"

fastrand = "1.5"

env_logger = "0.9"
log = "0.4"

petgraph = {version = "0.6", features = ["serde-1"]}

pest = "2.1"
pest_derive = "2.1"

once_cell = "1.8"

[dev-dependencies]
springql-foreign-service = {path = "../foreign-service"}
springql-test-logger = {path = "../test-logger"}

pretty_assertions = "1.0"

regex = "1.5"
